name: Check and Add Dependabot

on:
  push:
    branches:
      - main  # Change to your default branch
  workflow_dispatch:  # Allows manual triggering of the workflow
  
jobs:
  check-add-dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Check and Add Dependabot
        uses: abhipost12/Dependabot_composite@main 
       
